name: build

on: 
  workflow_dispatch:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_jar:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: "20"
          distribution: "oracle"
          cache: maven

      - name: Build with maven
        run: mvn clean package -Dmaven.test.skip

      - name: Copy Artifact
        run: mkdir staging && cp target/*.jar staging/interqu-spring-boot.jar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: staging/*.jar
          retention-days: 1 

  build_image:
    needs: build_jar
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
          
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-jar
          path: target

      - name: List files
        run: ls -R target

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          tags: lefanhu/interqu-spring-boot:latest
    
  deploy_image:
    needs: build_image
    runs-on: ubuntu-latest

    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd interqu
            docker compose pull
            docker compose up -d
            docker ps
