name: build-test

on: 
  workflow_dispatch:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          java-version: "20"
          distribution: "oracle"
          cache: maven

      - name: Build with maven
        run: mvn clean package -Dmaven.test.skip